#!/bin/sh

################################################################################
# LastPass Menu
#   Uses rofi or dmenu (if rofi is not found) to select a LastPass account and
#   copy its password to the X clipboard using xclip.
#
#   If you add any command line arguments, then this script will suppress
#   the final information message telling the user that the password has
#   been copied to the clipboard.
#
# Convenience / security note:
#   This script does not pass --trust to "lpass login". To prevent lpass-cli
#   from asking you for a second form of authentication, please run "lpass login
#   --trust" in a console once to configure lpass-cli to trust your computer. Be
#   aware that this may expire after 30 days. You may add --trust to the "lpass
#   login" call in this script if you understand the security implications of
#   doing so.
#
# Dependencies:
#   - lpass-cli
#   - rofi or dmenu (prefers rofi by default if it is found)
#   - zenity
#   - Clipboard program compatible with "lpass show -c" (such as xclip)
################################################################################
# Copyright 2017 Joshua Taylor <taylor.joshua88@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

rofi -version &> /dev/null

if [ $? -ne 0 ]; then
    MENU_CMD="dmenu"
    MENU_ARGS=
else
    MENU_CMD="rofi"
    MENU_ARGS=("-dmenu" "-p lpass:")
fi

lpass status

if [ $? -ne 0 ]; then
    lpass sync
    if [ $? -ne 0 ]; then
        notify-send -t 5000 -a "Last Pass" "Password" "No action taken"
        exit
    fi
#    ZENITY_INPUT="$(zenity --entry --text='Please enter your LastPass username:')"
#
#    if [ -z "$ZENITY_INPUT" ]; then
#        exit
#    fi
#
#    lpass login "$ZENITY_INPUT"
#
#    if [ $? -ne 0 ]; then
#        zenity --error --text="Failed to login to LastPass. Please check your credentials and try again."
#        exit
#    fi
fi

ROFI_SELECTION="$(lpass ls --format '•%an' | grep '•' | tr '•' '\n' | sed '/^$/d' | ${MENU_CMD} ${MENU_ARGS[@]})"

if [ -z "${ROFI_SELECTION}" ]; then
    exit
fi

lpass show -c --password "${ROFI_SELECTION}"

if [ $? -ne 0 ]; then
        notify-send -t 5000 -a "Last Pass" "Password" "Sync Succesful but no password copied to clipboard"
else
    if [ $# -lt 1 ]; then
        notify-send -t 5000 -a "Last Pass" "Password" "Password copied to clipboard."
    fi
    fi
#=======
##!/bin/bash
#
#
#selection=`echo -e $(lpass ls | awk -F '[/[]' '{print $(NF-1)"\\\n"}') | rofi -dmenu -i`
#
#if [ "$selection" != "" ]; then
#    lpass show -c --password $selection &
#fi
#>>>>>>> b655bbd7a7e336ac15a1be25c86388cf2c41c8a2
